### ISSUE TITLE
How to address a single file instead of all files within a directory?

### ISSUE THREAD

**Issue by WernMich** [Switajski/wakiga#1]
https://github.com/Switajski/wakiga/blob/917a6d4f7f7615094f65eed39a0ce751e6f1d79f/src/pages/standort.js#L13

Hi Marek,

do you have an idea how to address a single word file using Gatsbys gatsby-transformer-ms-word plugin? I did not find the defintion of "allDocx" object, neither in gatsby-transformer-ms-word, nor in mammoth.js nor gatsby itself. Where does this come from?

Best,
Michael

**Comment by Switajski** [comment]
`allDocx(filter: {name: {eq: "Neuer"}}) {
    edges {
      node {
        id
        name
      }
    }
  }`
Would do the thing.

Having local dev server started, [http://localhost:8000/___graphql](http://localhost:8000/___graphql) will guide you through creating queries in GraphQL:
<img width="1081" alt="Screenshot 2020-05-06 at 21 45 07" src="https://user-images.githubusercontent.com/4365453/81221269-e6748c00-8fe2-11ea-82d9-7f8fe2d503f9.png">

As ever,
Marek
